# Used Car Price

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('../data/carcsvdata/car details v4.csv')
df.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

### Checking data for any EDA required.

In [5]:
df[df.isnull().any(axis=1)]

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
6,Mercedes-Benz,CLA 200 Petrol Sport,1898999,2015,47000,Petrol,Automatic,Mumbai,White,Second,Individual,1991 cc,181 bhp @ 5500 rpm,300 Nm @ 1200 rpm,FWD,4630.0,1777.0,1432.0,5.0,NaN
33,Honda,CR-V 2.4 AT,860000,2013,67000,Petrol,Automatic,Mumbai,Brown,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,Audi,A4 2.0 TDI (143 bhp),1250000,2012,50000,Diesel,Automatic,Mumbai,White,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,BMW,X5 xDrive30d Pure Experience (5 Seater),2950000,2015,84700,Diesel,Automatic,Navi Mumbai,Black,Second,Individual,2993 cc,258 bhp @ 4000 rpm,560 Nm @ 1500 rpm,AWD,4886.0,1938.0,1762.0,5.0,NaN
94,Mercedes-Benz,GLC 220 d Sport,3900000,2018,83400,Diesel,Automatic,Hyderabad,White,Second,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025,Honda,Accord 2.4 iVtec AT,195000,2008,57885,Petrol,Automatic,Delhi,Beige,First,Individual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2032,Land Rover,Range Rover Velar 2.0 S Petrol 250,8900000,2020,88000,Petrol,Automatic,Mumbai,White,First,Individual,1997 cc,247 bhp @ 5500 rpm,365 Nm @ 1500 rpm,AWD,4797.0,2032.0,1665.0,5.0,NaN
2035,Maruti Suzuki,Wagon R LXi,265000,2011,41000,Petrol,Manual,Pune,Brown,Second,Individual,998 cc,68@6200,90@3500,NaN,3539.0,1475.0,1700.0,5.0,35.0
2052,Hyundai,i20 Sportz 1.4 CRDI,409999,2014,68000,Diesel,Manual,Agra,Silver,First,Individual,1396 cc,90@4000,220@1750,NaN,3940.0,1710.0,1505.0,5.0,45.0
2058,Mahindra,Bolero Power Plus ZLX [2016-2019],670000,2017,72000,Diesel,Manual,Guwahati,White,First,Individual,1493 cc,70 bhp @ 3600 rpm,195 Nm @ 1400 rpm,RWD,3995.0,1745.0,1880.0,7.0,NaN

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                2059 non-null   str
 1   Model               2059 non-null   str
 2   Price               2059 non-null   int64
 3   Year                2059 non-null   int64
 4   Kilometer           2059 non-null   int64
 5   Fuel Type           2059 non-null   str
 6   Transmission        2059 non-null   str
 7   Location            2059 non-null   str
 8   Color               2059 non-null   str
 9   Owner               2059 non-null   str
 10  Seller Type         2059 non-null   str
 11  Engine              1979 non-null   str
 12  Max Power           1979 non-null   str
 13  Max Torque          1979 non-null   str
 14  Drivetrain          1923 non-null   str
 15  Length              1995 non-null   float64
 16  Width               1995 non-null   float64
 17  Height              1995 non-null   float64
 18  Seating Capacity    1995 non-null   float64
 19  Fuel Tank Capacity  1946 non-null   float64
dtypes: float64(5), int64(3), str(12)
memory usage: 321.8 KB

#### Enconding and standardization needed, lots of rows with NaN values, have to fix.

In [8]:
df.describe()

,Price,Year,Kilometer,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
count,2.059000e+03,2059.000000,2.059000e+03,1995.000000,1995.000000,1995.000000,1995.000000,1946.000000
mean,1.702992e+06,2016.425449,5.422471e+04,4280.860652,1767.991980,1591.735338,5.306266,52.002210
std,2.419881e+06,3.363564,5.736172e+04,442.458507,135.265825,136.073956,0.822170,15.110198
min,4.900000e+04,1988.000000,0.000000e+00,3099.000000,1475.000000,1165.000000,2.000000,15.000000
25%,4.849990e+05,2014.000000,2.900000e+04,3985.000000,1695.000000,1485.000000,5.000000,41.250000
50%,8.250000e+05,2017.000000,5.000000e+04,4370.000000,1770.000000,1545.000000,5.000000,50.000000
75%,1.925000e+06,2019.000000,7.200000e+04,4629.000000,1831.500000,1675.000000,5.000000,60.000000
max,3.500000e+07,2022.000000,2.000000e+06,5569.000000,2220.000000,1995.000000,8.000000,105.000000

In [9]:
df.duplicated().sum()

np.int64(0)

##### No duplicates, no absurd values seen in describe.

In [12]:
df.columns

Index(['Make', 'Model', 'Price', 'Year', 'Kilometer', 'Fuel Type',
       'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Engine',
       'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height',
       'Seating Capacity', 'Fuel Tank Capacity'],
      dtype='str')

In [14]:
df = df.drop(columns=['Model', 'Engine'])

In [18]:
numeric_features = df.select_dtypes(include='number').columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 8 numerical features : ['Price', 'Year', 'Kilometer', 'Length', 'Width', 'Height', 'Seating Capacity', 'Fuel Tank Capacity']

We have 10 categorical features : ['Make', 'Fuel Type', 'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Max Power', 'Max Torque', 'Drivetrain']

In [19]:
df = df.dropna()

In [24]:
print(df.shape)
df.head()

(1874, 18)

,Make,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

#### Got rid of NaN values by just removing them, removed 'Model' because the value of the column is in 'Make' and dropped 'Engine' b/c I feel the value is in 'Max Power' and 'Max Torque'. Going to multiply length, width, height to get volume so I can drop those three columns and have to see how to fix 'Max Power' and 'Max Torque', if there isn't a large amount of variation in values I might just treat it as a categorical value.

In [25]:
df['Volume'] = df['Length'] * df['Width'] * df['Height']
df = df.drop(columns=['Length', 'Width', 'Height'])

In [27]:
df['Volume'] = (df['Volume']/1000)
## For max power
df['Power_bhp'] = df['Max Power'].str.extract(r'(\d+\.?\d*)\s*bhp').astype(float)
df['Power_rpm'] = df['Max Power'].str.extract(r'@\s*(\d+\.?\d*)\s*rpm').astype(float)
## For max torque
df['Torque_Nm'] = df['Max Torque'].str.extract(r'(\d+\.?\d*)\s*Nm').astype(float)
df['Torque_rpm'] = df['Max Torque'].str.extract(r'@\s*(\d+\.?\d*)\s*rpm').astype(float)

In [28]:
df.head()

,Make,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Max Power,Max Torque,Drivetrain,Seating Capacity,Fuel Tank Capacity,Volume,Power_bhp,Power_rpm,Torque_Nm,Torque_rpm
0,Honda,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,5.0,35.0,1.008832e+07,87.0,6000.0,109.0000,4500.0
1,Maruti Suzuki,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,5.0,42.0,1.052972e+07,74.0,4000.0,190.0000,2000.0
2,Hyundai,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,5.0,35.0,8.863016e+06,79.0,6000.0,112.7619,4000.0
3,Toyota,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,5.0,37.0,1.052663e+07,82.0,6000.0,113.0000,4200.0
4,Toyota,1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,7.0,55.0,1.555376e+07,148.0,3400.0,343.0000,1400.0

In [29]:
df[['Power_bhp', 'Power_rpm', 'Torque_Nm', 'Torque_rpm']].isnull().sum()

Power_bhp     70
Power_rpm     72
Torque_Nm     70
Torque_rpm    70
dtype: int64

In [30]:
df[df['Power_bhp'].isnull()]['Max Power'].unique()
df[df['Torque_Nm'].isnull()]['Max Torque'].unique()

<StringArray>
['240@3000', '500@1600', '146@4600', '277@1700', '215@3600', '190@2000',
 '535@1600', '540@1600', '343@1400',  '84@3500', '111@4000', '113@4500',
 '245@5000', '170@3500',  '48@3000', '290@1800', '323@2000', '410@2000',
 '350@2400', '480@1750', '170@4200', '350@1750', '247@1800', '160@2000',
  '99@2800',  '77@4500', '456@1400']
Length: 27, dtype: str

In [31]:
df = df.dropna(subset=['Power_bhp', 'Power_rpm', 'Torque_Nm', 'Torque_rpm'])

In [32]:
df = df.drop(columns=['Max Power', 'Max Torque'])

In [34]:
print(df.shape)
df.isnull().sum()

(1802, 18)

Make                  0
Price                 0
Year                  0
Kilometer             0
Fuel Type             0
Transmission          0
Location              0
Color                 0
Owner                 0
Seller Type           0
Drivetrain            0
Seating Capacity      0
Fuel Tank Capacity    0
Volume                0
Power_bhp             0
Power_rpm             0
Torque_Nm             0
Torque_rpm            0
dtype: int64

In [35]:
df.head()

,Make,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Drivetrain,Seating Capacity,Fuel Tank Capacity,Volume,Power_bhp,Power_rpm,Torque_Nm,Torque_rpm
0,Honda,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,FWD,5.0,35.0,1.008832e+07,87.0,6000.0,109.0000,4500.0
1,Maruti Suzuki,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,FWD,5.0,42.0,1.052972e+07,74.0,4000.0,190.0000,2000.0
2,Hyundai,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,FWD,5.0,35.0,8.863016e+06,79.0,6000.0,112.7619,4000.0
3,Toyota,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,FWD,5.0,37.0,1.052663e+07,82.0,6000.0,113.0000,4200.0
4,Toyota,1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,RWD,7.0,55.0,1.555376e+07,148.0,3400.0,343.0000,1400.0

In [36]:
numeric_features = df.select_dtypes(include='number').columns.tolist()
categorical_features = df.select_dtypes(include=['object', 'category']).columns.tolist()

print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 10 numerical features : ['Price', 'Year', 'Kilometer', 'Seating Capacity', 'Fuel Tank Capacity', 'Volume', 'Power_bhp', 'Power_rpm', 'Torque_Nm', 'Torque_rpm']

We have 8 categorical features : ['Make', 'Fuel Type', 'Transmission', 'Location', 'Color', 'Owner', 'Seller Type', 'Drivetrain']

In [38]:
df.to_csv('../data/carcsvdata/cleaned_car_data.csv', index=False)

#### I wanted to do the model training in a different .ipynb file to keep things clean, enconding + standardization will happen there.